version: '3'
services:
  {{cookiecutter.project_slug}}:
    container_name: {{cookiecutter.project_slug}}
    image: {{cookiecutter.project_slug}}:dev
    build:
      context: .
    ports:
      - "{{cookiecutter.api_port}}:{{cookiecutter.api_port}}"
    networks:
      - development
    volumes:
      - .:/home/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}
      - /home/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}.egg-info
    tty: true
    stdin_open: true
    entrypoint: "/bin/bash"
    command: >
      -c "../util/wait-for-it.sh db:5432 &&
      alembic -c local-settings.ini upgrade heads &&
      pserve settings.ini --reload"
  db:
    container_name: {{cookiecutter.project_slug}}-db
    image: postgres:13
    ports:
      - "{{cookiecutter.db_port}}:5432"
    networks:
      - development
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}
      - POSTGRES_PASSWORD=testing123
      - POSTGRES_DB={{cookiecutter.project_slug}}
  cache:
    container_name: {{cookiecutter.project_slug}}-cache
    image: redis:6
    ports:
      - "{{cookiecutter.cache_port}}:6379"
    networks:
      - development
  api-docs:
    container_name: {{cookiecutter.project_slug}}-api-docs
    image: swaggerapi/swagger-ui
    ports:
      - "{{cookiecutter.api_docs_port}}:8080"
    networks:
      - development
    environment:
      API_URL: http://localhost:3141/openapi 
networks:
  development:
